media:
  input: public/media
  output: /media

content:
  - name: projects
    label: Projets
    type: collection
    path: src/content/projects
    filename: "{slug}.md"
    view:
      fields: [order, title]
      sort:
        - order
    fields:
      - { name: order, label: Ordre, type: number }
      - { name: title, label: Titre, type: string }
      - name: cover
        label: Image
        type: image
      - name: tags
        label: Tags
        type: string
        list: true
      - { name: isOngoing, label: "Mission en cours", type: boolean }
      - name: testimonials
        label: Témoignages
        type: object
        list: true
        fields:
          - {
              name: quote,
              label: Citation,
              type: rich-text,
              options: { format: html },
            }
          - { name: author, label: Auteur, type: string }
          - { name: lang, label: "Langue (en/fr)", type: string }
