ignoredBuiltDependencies:
  - '@percy/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
