name: Run visual testing

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  visual-testing:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'visual-testing') || startsWith(github.head_ref, 'renovate/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Deploy
        id: cloudflare-preview-deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=yuna-work

      - name: Print pages-deployment-alias-url
        env:
          DEPLOYMENT_URL: ${{ steps.cloudflare-preview-deploy.outputs.deployment-url }}
          DEPLOYMENT_ALIAS_URL: ${{ steps.cloudflare-preview-deploy.outputs.pages-deployment-alias-url }}
        run: |
          echo $DEPLOYMENT_URL
          echo $DEPLOYMENT_ALIAS_URL

      #- name: Take yuna.work screenshots and upload them to Percy
      #  run: |
      #    pnpm wait-on "https-get://${CLOUDFLARE_PREVIEW_HOST}" --httpTimeout=2m
      #    pnpm percy snapshot .percy.mjs --verbose
      #  env:
      #    PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      #    DEPLOYMENT_ALIAS_URL:
      #    CLOUDFLARE_PREVIEW_HOST: ${{ steps.cloudflare-preview-deploy.outputs.preview_host }}
      #    CLOUDFLARE_PREVIEW_URL: ${{ steps.cloudflare-preview-deploy.outputs.preview_url }}
      #    ASTRO_PREVIEW_SERVER_PORT_FOR_VISUAL_TESTING: 4321
